In [1]:
#### Create an array of 10 zeros 

In [5]:
import numpy as np

In [5]:
np.zeros(0)

array([], dtype=float64)

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
#### Create an array of 10 ones

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
#### Create an array of 10 fives

In [21]:
np.ones(10)+4

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [23]:
#### Create an array of the integers from 10 to 50

In [27]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [29]:
#### Create an array of all the even integers from 10 to 50

In [31]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [33]:
#### Create a 3x3 matrix with values ranging from 0 to 8

In [35]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
#### Create a 3x3 identity matrix

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
#### Use NumPy to generate a random number between 0 and 1

In [53]:
np.random.rand(2)

array([0.01351985, 0.58642765])

In [55]:
#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [65]:
np.random.randn(5,5)

array([[ 0.97355244, -0.92724806, -0.08436287,  0.6600075 ,  0.48225712],
       [-0.44035417,  0.57334851,  0.28635318,  0.1900481 , -1.00919673],
       [-1.05124286, -1.25005294,  1.98336649, -0.76063358, -0.88160419],
       [ 1.0265781 , -1.78997271,  0.77225729,  0.34477381,  1.00631669],
       [ 1.3356861 ,  0.48330649, -1.20305961, -0.75774789,  2.23587042]])

In [67]:
#### Create the following matrix:

In [87]:
np.linspace(0.01,1.0,100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [89]:
#### Create an array of 20 linearly spaced points between 0 and 1:

In [91]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [99]:
 #WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
#array([[12, 13, 14, 15],
 #      [17, 18, 19, 20],
 #      [22, 23, 24, 25]])

In [109]:
np.arange(12,26).reshape(3,4)

ValueError: cannot reshape array of size 14 into shape (3,4)

In [111]:
#array([[ 1,  2,  3,  4,  5],
 #      [ 6,  7,  8,  9, 10],
  #     [11, 12, 13, 14, 15],
   #    [16, 17, 18, 19, 20],
  #     [21, 22, 23, 24, 25]])

In [13]:
data=np.arange(1,26).reshape(5,5)

In [15]:
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
data[2:5,1:6]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [31]:
data[3,4]

20

In [39]:
data[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [41]:
data[4:,0:4]

array([[21, 22, 23, 24]])

In [45]:
data[3:,0:4]

array([[16, 17, 18, 19],
       [21, 22, 23, 24]])

In [49]:
data.sum()

325

In [51]:
data.std()

7.211102550927978

In [57]:
data.sum(axis=1)

array([ 15,  40,  65,  90, 115])